# Generated by Django 4.2.15 on 2024-08-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='recipes',
        ),
    ]
